In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [8]:
df_train =  pd.read_csv('../input/twitter-separated/train_twitter.csv')
df_test =  pd.read_csv('../input/twitter-separated/test_twitter.csv')

In [7]:
import string

def punc(s):
    table = str.maketrans(dict.fromkeys(string.punctuation))  # OR {key: None for key in string.punctuation}
    new_s = s.translate(table)   
    return new_s

In [9]:
df_train

                                              description  category
0       she say she like me cuz ima real man . . . . ....         5
1       babygirl as jiggling dropping it low doing the...         1
2       my only talent is being able to do both the uw...         2
3       sobie ade buat postage rini pat pat jom all re...         2
4       i should make a video on that can it be top nu...         1
...                                                   ...       ...
120851  wrestling make me feel like i m wearing a tinf...         6
120852  the weirdest emotion is missing something that...         6
120853  say goodbye to the new me i m goin back to bei...         6
120854  u re playing with me without knowing that i am...         7
120855  wow u have a polaroid and the camera quality i...         7

[120856 rows x 2 columns]

In [13]:
df_test

                                                       0  1
0      i d rather have a wedding and honeymoon scene ...  7
1      unfortunately i ate my half so the rest is vin...  4
2      i mean wa i supposed to think of you like that...  7
3      aight ima pass . . . kinda hard watchin when t...  4
4      just a head up i am not gonna be making any ap...  5
...                                                  ... ..
21323  wishing everyone a prosperous month of april y...  6
21324  did my in the first few day in avoidance of ju...  1
21325  wauw i am taking your name off the list if u g...  3
21326  that dream was wild i don t think i ll ever re...  7
21327  makes you wish we were working on espnews toni...  1

[21328 rows x 2 columns]

In [14]:
df_train['description'] = df_train['description'].map(punc)
df_test['0'] = df_test['0'].map(punc)

In [15]:
df_train

                                              description  category
0       she say she like me cuz ima real man      no l...         5
1       babygirl as jiggling dropping it low doing the...         1
2       my only talent is being able to do both the uw...         2
3       sobie ade buat postage rini pat pat jom all re...         2
4       i should make a video on that can it be top nu...         1
...                                                   ...       ...
120851  wrestling make me feel like i m wearing a tinf...         6
120852  the weirdest emotion is missing something that...         6
120853  say goodbye to the new me i m goin back to bei...         6
120854  u re playing with me without knowing that i am...         7
120855  wow u have a polaroid and the camera quality i...         7

[120856 rows x 2 columns]

In [16]:
df_test

                                                       0  1
0      i d rather have a wedding and honeymoon scene ...  7
1      unfortunately i ate my half so the rest is vin...  4
2       i mean wa i supposed to think of you like that    7
3      aight ima pass    kinda hard watchin when the ...  4
4      just a head up i am not gonna be making any ap...  5
...                                                  ... ..
21323  wishing everyone a prosperous month of april y...  6
21324  did my in the first few day in avoidance of ju...  1
21325  wauw i am taking your name off the list if u g...  3
21326  that dream was wild i don t think i ll ever re...  7
21327  makes you wish we were working on espnews toni...  1

[21328 rows x 2 columns]

In [18]:
df_train.to_csv('train_twitter',index=False)
df_test.to_csv('test_twitter',index=False)